-- Replace <SCHEMA> with clients Schema NAME (CLIENT_SCHEMA)
-- Replace <ANALYST_SCHEMA> with clients ANALYST schema
-- Replace <POPULATION_ID> with clients population ID

SELECT DISTINCT CODIFIED_VALUES.SOURCE_DESCRIPTION AS SOURCE_DESCRIPTION,
                SRC.SOURCE_KEY,
                'CQAMD' AS DOCUMENT_TYPE,
                CODIFIED_VALUES.RAW_CODE_DISPLAY AS RAW_CODE_DISPLAY,
                NULL AS RAW_CODE_ALT_DISPLAY,
                CODIFIED_VALUES.RAW_CODE_ID,
                CASE
                    WHEN SYS.CODE_SYSTEM_NAME IS NULL THEN CODIFIED_VALUES.RAW_CODE_SYSTEM_ID
                    ELSE SYS.CODE_SYSTEM_NAME
                END AS RAW_CODE_SYSTEM_NAME,
                CODIFIED_VALUES.RAW_CODE_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                CASE
                    WHEN (COM.RAW_CODE_SYSTEM_COMMON_NAME IS NULL
                          AND SYS.CODE_SYSTEM_NAME IS NULL) THEN CODIFIED_VALUES.RAW_CODE_SYSTEM_ID
                    WHEN COM.RAW_CODE_SYSTEM_COMMON_NAME IS NULL THEN SYS.CODE_SYSTEM_NAME
                    ELSE COM.RAW_CODE_SYSTEM_COMMON_NAME
                END AS RAW_CODE_SYSTEM_COMMON_NAME,
                CODIFIED_VALUES.ACTIVITY_COUNT,
                'Unmapped' AS MAPPING_STATUS,
                NULL AS ORPHAN,
                'PCST' AS TEAM,
                'Unmapped' AS INTERNAL_REVIEW_SOURCE
FROM (
SELECT A.SOURCE_DESCRIPTION,
       A.CONDITION_RAW_CODE AS RAW_CODE_ID,
       A.CONDITION_TYPE_DISPLAY AS RAW_CODE_DISPLAY,
       A.CONDITION_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.CONDITION_CODE AS STD_CODE_ID,
       SPLIT_PART(SPLIT_PART(A.CONDITION_ID,':',2),'/',1) AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_CONDITION A
WHERE A.POPULATION_ID='<POPULATION_ID>'
AND A.CONDITION_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         SPLIT_PART(SPLIT_PART(A.CONDITION_ID,':',2),'/',1)
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.NAME_RAW_CODE AS RAW_CODE_ID,
       A.NAME_DISPLAY AS RAW_CODE_DISPLAY,
       A.NAME_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.NAME_CODE AS STD_CODE_ID,
       A.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION A
WHERE A.POPULATION_ID = '<POPULATION_ID>'
AND A.NAME_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         6
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       B.ORIG_CODIFIED_VALUE_RAW_CODE AS RAW_CODE_ID,
       B.ORIG_CODIFIED_VALUE_DISPLAY AS RAW_CODE_DISPLAY,
       B.ORIG_CODIFIED_VALUE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       B.ORIG_CODIFIED_VALUE_CODE AS STD_CODE_ID,
       A.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION A
JOIN <SCHEMA>.PH_F_QUESTIONNAIRE_ANSWER B ON (A.QUESTION_ID = B.QUESTION_ID
                                                      AND A.POPULATION_ID = B.POPULATION_ID
                                                      AND A.EMPI_ID = B.EMPI_ID)
WHERE A.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.ALLERGEN_RAW_CODE AS RAW_CODE_ID,
       A.ALLERGEN_DISPLAY AS RAW_CODE_DISPLAY,
       A.ALLERGEN_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.ALLERGEN_CODE AS STD_CODE_ID,
       SPLIT_PART(SPLIT_PART(ALLERGY_ID,':',2),'/',1) AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_ALLERGY A
WHERE A.POPULATION_ID='<POPULATION_ID>'
AND A.ALLERGEN_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         SPLIT_PART(SPLIT_PART(A.ALLERGY_ID,':',2),'/',1)
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.DRUG_RAW_CODE AS RAW_CODE_ID,
       A.DRUG_DISPLAY AS RAW_CODE_DISPLAY,
       A.DRUG_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.DRUG_CODE AS STD_CODE_ID,
       SPLIT_PART(SPLIT_PART(A.MEDICATION_ID,':',2),'/',1) AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_MEDICATION A
WHERE A.POPULATION_ID='<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         SPLIT_PART(SPLIT_PART(A.MEDICATION_ID,':',2),'/',1)
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.TYPE_RAW_CODE AS RAW_CODE_ID,
       A.TYPE_DISPLAY AS RAW_CODE_DISPLAY,
       A.TYPE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.TYPE_CODE AS STD_CODE_ID,
       A.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_DOCUMENT_REFERENCE A
WHERE A.POPULATION_ID='<POPULATION_ID>'
AND A.TYPE_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         6
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.ENCOUNTER_TYPE_RAW_CODE AS RAW_CODE_ID,
       A.ENCOUNTER_TYPE_DISPLAY AS RAW_CODE_DISPLAY,
       A.ENCOUNTER_TYPE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.ENCOUNTER_TYPE_CODE AS STD_CODE_ID,
       A.PARTITION_ID AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_ENCOUNTER A
WHERE A.POPULATION_ID = '<POPULATION_ID>'
AND A.ENCOUNTER_TYPE_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         6
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.PROCEDURE_RAW_CODE AS RAW_CODE_ID,
       A.PROCEDURE_DISPLAY AS RAW_CODE_DISPLAY,
       A.PROCEDURE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.PROCEDURE_CODE AS STD_CODE_ID,
       SPLIT_PART(SPLIT_PART(A.PROCEDURE_ID,':',2),'/',1) AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_PROCEDURE A
WHERE A.POPULATION_ID = '<POPULATION_ID>'
AND A.PROCEDURE_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         SPLIT_PART(SPLIT_PART(A.PROCEDURE_ID,':',2),'/',1)
		 HAVING COUNT(*) >= '100'
UNION ALL
SELECT A.SOURCE_DESCRIPTION,
       A.IMMUNIZATION_RAW_CODE AS RAW_CODE_ID,
       A.IMMUNIZATION_DISPLAY AS RAW_CODE_DISPLAY,
       A.IMMUNIZATION_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.IMMUNIZATION_CODE AS STD_CODE_ID,
       SPLIT_PART(SPLIT_PART(A.IMMUNIZATION_ID,':',2),'/',1) AS DATA_PARTITION_ID,
       COUNT(*) AS ACTIVITY_COUNT
FROM <SCHEMA>.PH_F_IMMUNIZATION A
WHERE A.POPULATION_ID = '<POPULATION_ID>'
AND A.IMMUNIZATION_CODE IS NULL
GROUP BY 1,
         2,
         3,
         4,
         5,
         SPLIT_PART(SPLIT_PART(A.IMMUNIZATION_ID,':',2),'/',1)
		 HAVING COUNT(*) >= '100') AS CODIFIED_VALUES
LEFT JOIN
    (SELECT DISTINCT SRC.SOURCE_DESCRIPTION,
                     SRC.DATA_PARTITION_ID,
                     SRC.SOURCE_KEY
     FROM
         (SELECT DISTINCT SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(REFERENCE_ID,':',2),'/',1) AS DATA_PARTITION_ID,
                SPLIT_PART(SPLIT_PART(RAW_ENTITY_KEY, ':', 2), '/',1) AS SOURCE_KEY
          FROM <SCHEMA>.PH_F_CONDITION
		  WHERE POPULATION_ID='<POPULATION_ID>'
          UNION ALL
          SELECT DISTINCT SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(REFERENCE_ID,':',2),'/',1) AS DATA_PARTITION_ID,
                CASE
                    WHEN RAW_ENTITY_KEY like '%/source:%' THEN SPLIT_PART(SPLIT_PART(RAW_ENTITY_KEY, 'source:', 2), '/', 1)
                    WHEN RAW_ENTITY_KEY like '%/tenant:%' THEN REPLACE(SPLIT_PART(SPLIT_PART(RAW_ENTITY_KEY, 'tenant:', 2), '/', 1), '_0', '')
                    WHEN RAW_ENTITY_KEY like '%/source_id:%' THEN SPLIT_PART(SPLIT_PART(RAW_ENTITY_KEY, 'source_id:', 2), '/', 1)
                END AS SOURCE_KEY
          FROM <SCHEMA>.PH_D_PERSON_DEMOGRAPHICS
		  WHERE POPULATION_ID='<POPULATION_ID>') SRC) SRC ON (CODIFIED_VALUES.DATA_PARTITION_ID = SRC.DATA_PARTITION_ID)
LEFT JOIN <ANALYST_SCHEMA>.DI_RAW_CODE_SYSTEM SYS ON (CODIFIED_VALUES.RAW_CODE_SYSTEM_ID = SYS.CODE_SYSTEM_ALIAS)
LEFT JOIN <ANALYST_SCHEMA>.DI_RAW_CODE_SYSTEM_COMMON_NAME COM ON SYS.CODE_SYSTEM_NAME LIKE ('%' || COM.RAW_CODE_SYSTEM_NAME)
WHERE CODIFIED_VALUES.STD_CODE_ID IS NULL
    AND CODIFIED_VALUES.RAW_CODE_ID IS NOT NULL
