WITH MEMBER_MONTH AS(
SELECT DISTINCT MM.POPULATION_ID,
                MM.CLAIM_SOURCE_DESCRIPTION,
                MM.BENEFIT_TYPE,
                MM.MONTH_DATE_ID,
                MM.EMPI_ID
FROM <ANALYST_SCHEMA>.DI_PR_MEMBER_MONTHS MM
WHERE MM.POPULATION_ID = '<POPULATION_ID>'
  AND MM.PLAN_NAME IS NOT NULL
  AND MM.PLAN_NAME NOT IN (<PLAN_NAME_EXCLUSION_LIST>)
  AND MM.CLAIM_SOURCE_DESCRIPTION IN (<ENROLLMENT_SOURCE_LIST>)
  AND MM.MONTH >= '<BEGIN_DATE>'
  AND MM.MONTH <= '<END_DATE>'
  AND MM.CMS_EXCLUSION_IND <> 1
  AND MM.BENEFIT_TYPE ILIKE '%MEDICAL%'
),

HOSPITAL_ADMISSION AS (
SELECT HA.EMPI_ID,
       HA.POPULATION_ID,
       HA.HOSPITAL_ADMISSION_ID,
       HA.ACUTE_DAYS,
       HA.ACUTE_IND,
       HA.EMERGENCY_IND,
       HA.EMERGENCY_ADMIT_IND
FROM <SCHEMA>.PH_F_HOSPITAL_ADMISSION HA
WHERE HA.POPULATION_ID = '<POPULATION_ID>'
)

SELECT HA.POPULATION_ID,
       C.SOURCE_DESCRIPTION,
       HA.EMPI_ID,
       C.INCURRED_FROM_MONTH_ID AS MONTH_DATE_ID,
       CASE
           WHEN MM.EMPI_ID IS NULL THEN 0
           ELSE 1
       END AS MEMBER_ENROLLED_IND,
       COUNT(DISTINCT CASE
                          WHEN HA.ACUTE_IND = 1 THEN HA.HOSPITAL_ADMISSION_ID
                      END) AS ACUTE_COUNT,
       SUM(DISTINCT CASE
                        WHEN HA.ACUTE_IND = 1 THEN HA.ACUTE_DAYS
                        ELSE 0
                    END) AS ACUTE_DAYS_TOTAL,
       AVG(DISTINCT CASE
                        WHEN HA.ACUTE_IND = 1 THEN HA.ACUTE_DAYS
                        ELSE 0
                    END) AS ACUTE_DAYS_AVG,
       COUNT(DISTINCT CASE
                          WHEN HA.EMERGENCY_ADMIT_IND = 1 THEN HA.HOSPITAL_ADMISSION_ID
                      END) AS ED_ADMIT_TO_IP_COUNT,
       COUNT(DISTINCT CASE
                          WHEN HA.EMERGENCY_IND = 1 THEN HA.HOSPITAL_ADMISSION_ID
                      END) AS ED_COUNT,
       COUNT(DISTINCT CASE
                          WHEN HA.EMERGENCY_ADMIT_IND = 0
                               AND HA.EMERGENCY_IND = 1 THEN HA.HOSPITAL_ADMISSION_ID
                      END) AS CATCH_N_RELEASE
FROM HOSPITAL_ADMISSION HA
INNER JOIN <SCHEMA>.PH_F_HOSPITAL_ADMISSION_RELATED_CLAIMS HARC ON (HA.EMPI_ID = HARC.EMPI_ID
                                                        AND HA.HOSPITAL_ADMISSION_ID = HARC.HOSPITAL_ADMISSION_ID)
INNER JOIN <SCHEMA>.PH_F_CLAIM C ON (HARC.EMPI_ID = C.EMPI_ID
                            AND HARC.CLAIM_ID = C.CLAIM_ID
                            AND HA.POPULATION_ID = C.POPULATION_ID)
LEFT JOIN MEMBER_MONTH MM ON (MM.EMPI_ID = C.EMPI_ID
                              AND MM.POPULATION_ID = C.POPULATION_ID
                              AND MM.CLAIM_SOURCE_DESCRIPTION = C.SOURCE_DESCRIPTION
                              AND MM.MONTH_DATE_ID = C.INCURRED_FROM_MONTH_ID)
WHERE NOT EXISTS
    (SELECT A.EMPI_ID
     FROM <SCHEMA>.PH_F_CMS_MEMBER_INFO A
     WHERE A.CMS_MEMBER_INFO_TYPE ='CMS_ACO_EXCLUSION_REASON'
       AND A.EFFECTIVE_PERIOD_START_DT_ID = C.INCURRED_FROM_MONTH_ID
       AND A.EMPI_ID = C.EMPI_ID )
GROUP BY 1,
         2,
         3,
         4,
         5