
WITH MEMBER_MONTH AS (
SELECT DISTINCT MM.POPULATION_ID,
                MM.ENROLLMENT_SOURCE_DESCRIPTION,
                MM.CLAIM_SOURCE_DESCRIPTION,
                MM.MONTH_DATE_ID,
                MM.EMPI_ID
FROM <ANALYST_SCHEMA>.DI_PR_MEMBER_MONTHS MM
WHERE MM.POPULATION_ID = '<POPULATION_ID>'
  AND MM.PLAN_NAME IS NOT NULL
  AND MM.PLAN_NAME NOT IN (<PLAN_NAME_EXCLUSION_LIST>)
  AND MM.CLAIM_SOURCE_DESCRIPTION IN (<ENROLLMENT_SOURCE_LIST>)
  AND MM.MONTH >= '<BEGIN_DATE>'
  AND MM.MONTH <= '<END_DATE>'
  AND MM.CMS_EXCLUSION_IND <> 1
  AND MM.BENEFIT_TYPE ILIKE '%MEDICAL%'
)

SELECT NOW() AS SNAPSHOT_DT_TM,
       '<SCHEMA>' AS CLIENT_SCHEMA,
       ED.POPULATION_ID,
       ED.EMPI_ID,
       ED.SOURCE_DESCRIPTION,
       CAST(REPLACE(CAST(CAST(DATE_TRUNC('MONTH', ED.INCURRED_DATE) AS DATE) AS VARCHAR), '-', '') AS INT) AS MONTH_DATE_ID,
       CASE
           WHEN MM.EMPI_ID IS NULL THEN 0
           ELSE 1
       END AS MEMBER_ENROLLED_IND,
       COUNT (DISTINCT CASE
                           WHEN ED.ACCOUNTABLE_VST_IND = 'TRUE' THEN ED.ENCOUNTER_ID
                           ELSE NULL
                       END) AS ACCOUNTABLE_PROVIDER_VISIT_COUNT,
             COUNT (DISTINCT CASE
                                 WHEN ED.NON_SPEC_IND = 'TRUE' THEN ED.ENCOUNTER_ID
                                 ELSE NULL
                             END) AS NON_SPECIALIST_VISIT_COUNT,
                   COUNT (DISTINCT CASE
                                       WHEN ED.SPEC_IND = 'TRUE' THEN ED.ENCOUNTER_ID
                                       ELSE NULL
                                   END) AS SPECIALIST_VISIT_COUNT
FROM <SCHEMA>.PH_F_ENCOUNTER_DETAIL ED
LEFT JOIN MEMBER_MONTH MM ON (MM.EMPI_ID = ED.EMPI_ID
                              AND MM.POPULATION_ID = ED.POPULATION_ID
                              AND MM.CLAIM_SOURCE_DESCRIPTION = ED.SOURCE_DESCRIPTION
                              AND MM.MONTH_DATE_ID = CAST(REPLACE(CAST(CAST(DATE_TRUNC('MONTH', ED.INCURRED_DATE) AS DATE) AS VARCHAR), '-', '') AS INT))
WHERE ED.INCURRED_DATE >= '<BEGIN_DATE>'
AND ED.INCURRED_DATE <= '<END_DATE>'
AND NOT EXISTS
    (SELECT A.EMPI_ID
     FROM <SCHEMA>.PH_F_CMS_MEMBER_INFO A
     WHERE A.CMS_MEMBER_INFO_TYPE ='CMS_ACO_EXCLUSION_REASON'
       AND A.EFFECTIVE_PERIOD_START_DT_ID = CAST(REPLACE(CAST(CAST(DATE_TRUNC('MONTH', ED.INCURRED_DATE) AS DATE) AS VARCHAR), '-', '') AS INT)
       AND A.EMPI_ID = ED.EMPI_ID)
GROUP BY 3,
         4,
         5,
         6,
         7