
SELECT NOW() AS SNAPSHOT_DT_TM,
       '<SCHEMA>' AS CLIENT_SCHEMA,
       MM.ENROLLMENT_SOURCE_DESCRIPTION,
       MM.SOURCE_DESCRIPTION AS CLAIM_SOURCE_DESCRIPTION,
       MM.POPULATION_ID,
       MM.EMPI_ID,
       MM.MONTH,
       MM.MONTH_DATE_ID::INT,
       MM.FIRST_DATE_OF_COVERAGE AS BEGIN_DATE,
       MM.LAST_DATE_OF_COVERAGE AS END_DATE,
       MM.DAYS_ELIGIBLE_IN_MONTH::INT,
       MM.PAYER_NAME,
       MM.PLAN_NAME,
       MM.BENEFIT_TYPE_CODE,
       MM.BENEFIT_TYPE,
       MM.EXCLUSION_IND::INT AS CMS_EXCLUSION_IND,
       MIN(MM.RAW_FILE) AS RAW_FILE,
       MIN(MM.MEMBER_ID) AS MEMBER_ID,
       MIN(MM.PBC_ID) AS PBC_ID
FROM <ANALYST_SCHEMA>.DI_MEMBER_MONTHS MM
WHERE MM.SOURCE_DESCRIPTION IN (<SOURCE_LIST>)
AND MM.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10,
         11,
         12,
         13,
         14,
         15,
         16;


WITH DATE_DATA AS (
SELECT MIN(DD.SQL_DATE) AS SQL_DATE,
       MIN(DD.SQL_DATE) AS MIN_SQL_DATE,
       MAX(DD.SQL_DATE) AS MAX_SQL_DATE
FROM <SCHEMA>.PH_D_DATE DD
WHERE DATEDIFF('MONTH', CURRENT_DATE, COALESCE(DD.SQL_DATE::DATE, CURRENT_DATE))>=-36
  AND DATEDIFF('MONTH', CURRENT_DATE, COALESCE(DD.SQL_DATE::DATE, CURRENT_DATE))<=0
GROUP BY DD.YEAR,
         DD.MONTH_NUMBER
)

SELECT NOW() AS SNAPSHOT_DT_TM,
       A.SOURCE_DESCRIPTION AS CLAIM_SOURCE_DESCRIPTION,
       A.POPULATION_ID,
       A.EMPI_ID,
       B.SQL_DATE AS MONTH,
       TO_CHAR(DATE_TRUNC('MONTH', B.SQL_DATE), 'YYYYMMDD')::INTEGER AS MONTH_DATE_ID,
       GREATEST(B.MIN_SQL_DATE, A.BEGIN_DATE + 1) AS BEGIN_DATE,
       LEAST(B.MAX_SQL_DATE, COALESCE(A.END_DATE + 1, CURRENT_DATE())) AS END_DATE,
       DATEDIFF(DAY, GREATEST(B.MIN_SQL_DATE, A.BEGIN_DATE + 1), LEAST(B.MAX_SQL_DATE, COALESCE(A.END_DATE + 1, CURRENT_DATE()))) + 1 AS DAYS_ELIGIBLE_IN_MONTH,
       A.PAYER_NAME,
       A.PLAN_NAME,
       '999' AS BENEFIT_TYPE_CODE,
       'Manual Pharmacy' AS BENEFIT_TYPE,
       0::INT AS CMS_EXCLUSION_IND,
       MIN(SPLIT_PART(A.RAW_ENTITY_KEY, 'mappingType:', 2)) AS RAW_FILE,
       MIN(A.MEMBER_ID) AS MEMBER_ID,
       MIN(A.PBC_ID) AS PBC_ID
FROM PH_F_PERSON_BENEFIT_COVERAGE A
LEFT OUTER JOIN DATE_DATA B ON CAST(A.BEGIN_DT_TM + 1 AS DATE) <= MAX_SQL_DATE
AND CASE
        WHEN A.END_DT_TM IS NULL
             OR A.END_DT_TM > CURRENT_DATE THEN CURRENT_DATE
        ELSE CAST(A.END_DT_TM + 1 AS DATE)
    END >= MIN_SQL_DATE
WHERE A.POPULATION_ID = '<POPULATION_ID>'
AND A.SOURCE_DESCRIPTION IN (<PHARMACY_COVERAGE_LIST>)
AND A.SOURCE_TYPE = 'ENROLLMENT'
AND (DATEDIFF('month', A.END_DATE, CURRENT_DATE()) <= 36
  OR A.END_DATE IS NULL)
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10,
         11,
         12,
         13,
         14;


UPDATE <ANALYST_SCHEMA>.DI_PR_MEMBER_MONTHS
SET
1 = CMS_EXCLUSION_IND
FROM
(SELECT DISTINCT CMI.EMPI_ID,
                   CMI.EFFECTIVE_PERIOD_START_DT_ID AS MONTH_DATE_ID
   FROM <SCHEMA>.PH_F_CMS_MEMBER_INFO CMI
   WHERE CMS_MEMBER_INFO_TYPE ilike '%exclusion%') UPDT
WHERE
DI_PR_MEMBER_MONTHS.EMPI_ID = UPDT.EMPI_ID
AND DI_PR_MEMBER_MONTHS.MONTH_DATE_ID = UPDT.MONTH_DATE_ID
AND (DI_PR_MEMBER_MONTHS.CLAIM_SOURCE_DESCRIPTION iLike '%CMS%'
     OR DI_PR_MEMBER_MONTHS.CLAIM_SOURCE_DESCRIPTION iLike '%MSSP%')