-- Replace <SCHEMA> with client schema
-- Replace <POPULATION_ID> with client's Population_id
-- Replace <CONTEXT_ID>

WITH VAC_ONTOLOGY AS
  (SELECT DISTINCT OA.ALIAS,
                   O.POPULATION_ID,
                   O.CODE_SYSTEM_ID,
                   O.CODE_OID
   FROM <SCHEMA>.PH_D_ONTOLOGY O
   JOIN <SCHEMA>.PH_D_ONTOLOGY_CONCEPT_ALIAS OA ON (O.CONCEPT_ID = OA.CONCEPT_ID
                                                           AND O.CONTEXT_ID = OA.CONTEXT_ID
                                                           AND O.POPULATION_ID = OA.POPULATION_ID
                                                           AND O.POPULATION_ID ='<POPULATION_ID>')
   WHERE OA.ALIAS LIKE '%_VAC'
     AND O.POPULATION_ID ='<POPULATION_ID>'
     AND O.CONTEXT_ID = '<CONTEXT_ID>')
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       MED_DISPENSE_ALIAS,
       COUNT (DISTINCT CASE
                           WHEN IMMUNIZATION_ALIAS IS NOT NULL THEN EMPI_ID
                       END) AS NUMERATOR,
             COUNT (DISTINCT CASE
                                 WHEN IMMUNIZATION_ALIAS IS NOT NULL
                                      AND IMM_SOURCE_TYPE = 'EMR' THEN EMPI_ID
                             END) AS EMR_NUMERATOR,
                   COUNT (DISTINCT EMPI_ID) AS DENOMINATOR
FROM
  (SELECT MED.POPULATION_ID,
          MED.EMPI_ID,
          MED_DISPENSE_ALIAS,
          IMMUNIZATION_ALIAS,
          MED.MED_DISPENSE_DATE,
          IMM.IMMUNIZATION_DATE,
          MED_DISPENSE_CODE,
          IMMUNIZATION_DRUG_CODE,
          IMM_SOURCE_TYPE
   FROM
     (SELECT O.ALIAS AS MED_DISPENSE_ALIAS,
             MD.EMPI_ID,
             MD.POPULATION_ID,
             WHEN_HANDED_OVER_DT_TM::DATE AS MED_DISPENSE_DATE,
             DRUG_CODE_CODE AS MED_DISPENSE_CODE
      FROM
        (SELECT MD.EMPI_ID,
                CLAIM_UID,
                MD.POPULATION_ID,
                SOURCE_TYPE,
                SOURCE_DESCRIPTION,
                WHEN_HANDED_OVER_DT_TM,
                DRUG_CODE_CODE,
                DRUG_CODE_CODING_SYSTEM_ID
         FROM <SCHEMA>.PH_F_MEDICATION_DISPENSE MD
         JOIN <SCHEMA>.PH_f_MEDICATION_DISPENSE_INGREDIENT MDI ON MD.MEDICATION_DISPENSE_ID = MDI.MEDICATION_DISPENSE_ID
         AND MD.EMPI_ID = MDI.EMPI_ID
         AND MD.POPULATION_ID = MDI.POPULATION_ID
         AND MD.POPULATION_ID ='<POPULATION_ID>'
         WHERE MD.SOURCE_TYPE = 'CLAIM'
           AND MD.POPULATION_ID ='<POPULATION_ID>'
           AND WHEN_HANDED_OVER_DT_TM <= CURRENT_DATE
           AND WHEN_HANDED_OVER_DT_TM >= CURRENT_DATE - 365
           AND EXISTS
             (SELECT 1
              FROM <SCHEMA>.PH_F_CLAIM C
              WHERE COALESCE(INCURRED_FROM_DATE, INCURRED_TO_DATE) <= CURRENT_DATE
                AND COALESCE(INCURRED_FROM_DATE, INCURRED_TO_DATE) >= CURRENT_DATE - 365
                AND FORM_TYPE = 'Rx'
                AND POPULATION_ID ='<POPULATION_ID>'
                AND MD.CLAIM_UID = C.CLAIM_UID
                AND MD.EMPI_ID = C.EMPI_ID
                AND MD.POPULATION_ID = C.POPULATION_ID
                AND MD.SOURCE_TYPE = C.SOURCE_TYPE
                AND MD.SOURCE_DESCRIPTION = C.SOURCE_DESCRIPTION))MD
      JOIN VAC_ONTOLOGY O ON O.CODE_OID = MD.DRUG_CODE_CODE
      AND O.CODE_SYSTEM_ID = MD.DRUG_CODE_CODING_SYSTEM_ID) MED
   LEFT JOIN
     (SELECT O2.ALIAS AS IMMUNIZATION_ALIAS,
             IMMUNIZATION_DRUG_CODE,
             I.EMPI_ID,
             I.POPULATION_ID,
             IMMUNIZATION_DATE AS IMMUNIZATION_DATE,
             SOURCE_TYPE AS IMM_SOURCE_TYPE
      FROM
        (SELECT SOURCE_TYPE,
                POPULATION_ID,
                EMPI_ID,
                COALESCE(IMMUNIZATION_CODE, DRUG_CODE) AS IMMUNIZATION_DRUG_CODE,
                COALESCE(IMMUNIZATION_CODING_SYSTEM_ID, DRUG_CODING_SYSTEM_ID) AS IMMUNIZATION_DRUG_CODING_SYSTEM_ID,
                IMMUNIZATION_DATE::DATE
         FROM <SCHEMA>.PH_F_IMMUNIZATION
         WHERE POPULATION_ID ='<POPULATION_ID>'
           AND IMMUNIZATION_DATE <= CURRENT_DATE
           AND IMMUNIZATION_DATE >= CURRENT_DATE - 370) I
      JOIN VAC_ONTOLOGY O2 ON O2.CODE_OID = I.IMMUNIZATION_DRUG_CODE
      AND O2.CODE_SYSTEM_ID = I.IMMUNIZATION_DRUG_CODING_SYSTEM_ID) IMM ON ABS(DATEDIFF(DAY, IMM.IMMUNIZATION_DATE, MED.MED_DISPENSE_DATE)) <= 5
   AND IMM.POPULATION_ID = MED.POPULATION_ID
   AND IMM.EMPI_ID = MED.EMPI_ID
   AND IMM.IMMUNIZATION_ALIAS = MED.MED_DISPENSE_ALIAS)A
GROUP BY 2
