-- Replace <SCHEMA> with clients Schema NAME
-- Replace <POPULATION_ID> with clients population ID
-- https://jira2.cerner.com/browse/HIDATAINT-24514

-- gets us data that is standardized. Used to identify potential reprocessing errors
WITH STANDARD_CODES AS(
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.ALLERGY_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.ALLERGEN_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.ALLERGEN_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_ALLERGY A
WHERE A.ALLERGEN_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.MEDICATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.DRUG_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.DRUG_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_MEDICATION A
WHERE A.DRUG_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.IMMUNIZATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.DRUG_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.DRUG_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_IMMUNIZATION A
WHERE A.DRUG_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.IMMUNIZATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.IMMUNIZATION_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.IMMUNIZATION_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_IMMUNIZATION A
WHERE A.IMMUNIZATION_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                A.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
                A.QUESTIONNAIRE_NAME_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.QUESTIONNAIRE_NAME_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION A
WHERE A.QUESTIONNAIRE_NAME_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                A.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
                A.NAME_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.NAME_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION A
WHERE A.NAME_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                A.PARTITION_ID AS DATA_PARTITION_ID,
                A.ENCOUNTER_TYPE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.ENCOUNTER_TYPE_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_ENCOUNTER A
WHERE A.ENCOUNTER_TYPE_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.PROCEDURE_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.PROCEDURE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.PROCEDURE_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_PROCEDURE A
WHERE A.PROCEDURE_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
UNION ALL
SELECT DISTINCT A.SOURCE_DESCRIPTION,
                SPLIT_PART(SPLIT_PART(A.CONDITION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                A.CONDITION_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
                A.CONDITION_RAW_CODE AS RAW_CODE_ID
FROM <SCHEMA>.PH_F_CONDITION A
WHERE A.CONDITION_CODE IS NOT NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
),

-- pulls back the unmapped code data
DATA_ACTIVITY AS (
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       A.POPULATION_ID,
       'ALLERGY' AS DATA_MODEL,
       'ALLERGEN_CODE' AS MODEL_ATTRIBUTE,
       A.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(A.ALLERGY_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       A.SOURCE_TYPE,
       A.ALLERGEN_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       A.ALLERGEN_RAW_CODE AS RAW_CODE_ID,
       A.ALLERGEN_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_ALLERGY A
WHERE A.ALLERGEN_CODE IS NULL
  AND A.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       M.POPULATION_ID,
       'MEDICATION' AS DATA_MODEL,
       'DRUG_CODE' AS MODEL_ATTRIBUTE,
       M.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(M.MEDICATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       M.SOURCE_TYPE,
       M.DRUG_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       M.DRUG_RAW_CODE AS RAW_CODE_ID,
       M.DRUG_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_MEDICATION M
WHERE M.DRUG_CODE IS NULL
  AND M.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       I.POPULATION_ID,
       'IMMUNIZATION' AS DATA_MODEL,
       'IMMUNIZATION_DRUG_CODE' AS MODEL_ATTRIBUTE,
       I.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(I.IMMUNIZATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       I.SOURCE_TYPE,
       I.DRUG_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       I.DRUG_RAW_CODE AS RAW_CODE_ID,
       I.DRUG_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_IMMUNIZATION I
WHERE I.DRUG_CODE IS NULL
  AND I.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       I.POPULATION_ID,
       'IMMUNIZATION' AS DATA_MODEL,
       'IMMUNIZATION_CODE' AS MODEL_ATTRIBUTE,
       I.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(I.IMMUNIZATION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       I.SOURCE_TYPE,
       I.IMMUNIZATION_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       I.IMMUNIZATION_RAW_CODE AS RAW_CODE_ID,
       I.IMMUNIZATION_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_IMMUNIZATION I
WHERE I.IMMUNIZATION_CODE IS NULL
  AND I.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       QQ.POPULATION_ID,
       'QUESTIONNAIRE QUESTION' AS DATA_MODEL,
       'QUESTIONNAIRE_NAME_CODE' AS MODEL_ATTRIBUTE,
       QQ.SOURCE_DESCRIPTION,
       QQ.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
       QQ.SOURCE_TYPE,
       QQ.QUESTIONNAIRE_NAME_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       QQ.QUESTIONNAIRE_NAME_RAW_CODE AS RAW_CODE_ID,
       QQ.QUESTIONNAIRE_NAME_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION QQ
WHERE QQ.QUESTIONNAIRE_NAME_CODE IS NULL
  AND QQ.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       QQ.POPULATION_ID,
       'QUESTIONNAIRE QUESTION' AS DATA_MODEL,
       'NAME_CODE' AS MODEL_ATTRIBUTE,
       QQ.SOURCE_DESCRIPTION,
       QQ.SOURCE_DATA_PARTITION_ID AS DATA_PARTITION_ID,
       QQ.SOURCE_TYPE,
       QQ.NAME_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       QQ.NAME_RAW_CODE AS RAW_CODE_ID,
       QQ.NAME_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_QUESTIONNAIRE_QUESTION QQ
WHERE QQ.NAME_CODE IS NULL
  AND QQ.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       E.POPULATION_ID,
       'ENCOUNTER' AS DATA_MODEL,
       'ENCOUNTER_TYPE_CODE' AS MODEL_ATTRIBUTE,
       E.SOURCE_DESCRIPTION,
       E.PARTITION_ID AS DATA_PARTITION_ID,
       E.SOURCE_TYPE,
       E.ENCOUNTER_TYPE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       E.ENCOUNTER_TYPE_RAW_CODE AS RAW_CODE_ID,
       E.ENCOUNTER_TYPE_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT (*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_ENCOUNTER E
WHERE E.ENCOUNTER_TYPE_CODE IS NULL
  AND E.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       P.POPULATION_ID,
       'PROCEDURE' AS DATA_MODEL,
       'PROCEDURE_CODE' AS MODEL_ATTRIBUTE,
       P.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(P.PROCEDURE_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       P.SOURCE_TYPE,
       P.PROCEDURE_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       P.PROCEDURE_RAW_CODE AS RAW_CODE_ID,
       P.PROCEDURE_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_PROCEDURE P
WHERE P.PROCEDURE_CODE IS NULL
  AND P.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
UNION ALL
SELECT '<SCHEMA>' AS CLIENT_SCHEMA,
       C.POPULATION_ID,
       'CONDITION' AS DATA_MODEL,
       'CONDITION_CODE' AS MODEL_ATTRIBUTE,
       C.SOURCE_DESCRIPTION,
       SPLIT_PART(SPLIT_PART(C.CONDITION_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
       C.SOURCE_TYPE,
       C.CONDITION_RAW_CODING_SYSTEM_ID AS RAW_CODE_SYSTEM_ID,
       C.CONDITION_RAW_CODE AS RAW_CODE_ID,
       C.CONDITION_DISPLAY AS RAW_CODE_DISPLAY,
       COUNT(*) AS RECORD_COUNT
FROM <SCHEMA>.PH_F_CONDITION C
WHERE C.CONDITION_CODE IS NULL
  AND C.POPULATION_ID = '<POPULATION_ID>'
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         10
),

-- breaks up the data to get us the source key (pcst) for each HealtheEDW source_description
SOURCE_KEYS AS (
SELECT DISTINCT SRC.SOURCE_DESCRIPTION,
                SRC.DATA_PARTITION_ID,
                SRC.SOURCE_KEY
FROM
  (SELECT DISTINCT SOURCE_DESCRIPTION,
                   SPLIT_PART(SPLIT_PART(C.REFERENCE_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                   SPLIT_PART(SPLIT_PART(C.RAW_ENTITY_KEY, ':', 2), '/', 1) AS SOURCE_KEY
   FROM <SCHEMA>.PH_F_CONDITION C
   WHERE C.POPULATION_ID='<POPULATION_ID>'
   UNION ALL SELECT DISTINCT PD.SOURCE_DESCRIPTION,
                             SPLIT_PART(SPLIT_PART(PD.REFERENCE_ID, ':', 2), '/', 1) AS DATA_PARTITION_ID,
                             CASE
                                 WHEN PD.RAW_ENTITY_KEY like '%/source:%' THEN SPLIT_PART(SPLIT_PART(PD.RAW_ENTITY_KEY, 'source:', 2), '/', 1)
                                 WHEN PD.RAW_ENTITY_KEY like '%/tenant:%' THEN REPLACE(SPLIT_PART(SPLIT_PART(PD.RAW_ENTITY_KEY, 'tenant:', 2), '/', 1), '_0', '')
                                 WHEN PD.RAW_ENTITY_KEY like '%/source_id:%' THEN SPLIT_PART(SPLIT_PART(PD.RAW_ENTITY_KEY, 'source_id:', 2), '/', 1)
                             END AS SOURCE_KEY
   FROM <SCHEMA>.PH_D_PERSON_DEMOGRAPHICS PD
   WHERE PD.POPULATION_ID='<POPULATION_ID>') SRC
)

-- MAIN QUERY --
SELECT DA.CLIENT_SCHEMA,
       DA.POPULATION_ID,
       SK.SOURCE_KEY,
       DA.SOURCE_DESCRIPTION,
       DA.DATA_MODEL,
       DA.MODEL_ATTRIBUTE,
       DA.SOURCE_TYPE,
       DA.RAW_CODE_SYSTEM_ID,
       DA.RAW_CODE_ID,
       DA.RAW_CODE_DISPLAY,
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM STANDARD_CODES SC
                   WHERE DA.SOURCE_DESCRIPTION = SC.SOURCE_DESCRIPTION
                     AND DA.RAW_CODE_ID = SC.RAW_CODE_ID
                     AND DA.RAW_CODE_SYSTEM_ID = SC.RAW_CODE_SYSTEM_ID) THEN TRUE
           ELSE FALSE
       END AS REPROCESSING_ISSUE,
       DA.RECORD_COUNT
FROM DATA_ACTIVITY DA
LEFT OUTER JOIN SOURCE_KEYS SK ON (DA.DATA_PARTITION_ID = SK.DATA_PARTITION_ID
                                   AND DA.SOURCE_DESCRIPTION = SK.SOURCE_DESCRIPTION)
